### ISSUE TITLE
defer h.pool.Put(gz)

### ISSUE THREAD

**Issue by mrauh** [phyber/negroni-gzip#6]
Hi, I think it would make sense to defer the call of h.pool.Put(gz), so it would become:

```go
gz := h.pool.Get().(*gzip.Writer)
defer h.pool.Put(gz)
```

**Comment by phyber** [comment]
You may be correct. The reasoning here is to ensure that that particular handler ends up back in the pool if a call between the `Get()` and the end of the function fails, correct?

**Comment by mrauh** [comment]
Yes, correct! Sorry that my explanation was missing. You can find an example of the usage on https://blog.cloudflare.com/dns-parser-meet-go-fuzzer/ (search for "bufpool").
